services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
    restart: unless-stopped
