toggle:
  target:
    entity:
      domain: select
      integration: friendly_scene_flipper

set_scene:
  target:
    entity:
      domain: select
      integration: friendly_scene_flipper
  fields:
    slot:
      required: true
      selector:
        select:
          options:
            - "a"
            - "b"
    scene_entity_id:
      required: true
      selector:
        entity:
          domain: scene

activate:
  target:
    entity:
      domain: select
      integration: friendly_scene_flipper
  fields:
    slot:
      required: true
      selector:
        select:
          options:
            - "a"
            - "b"

skip:
  target:
    entity:
      domain: select
      integration: friendly_scene_flipper
  fields:
    slot:
      required: true
      selector:
        select:
          options:
            - "a"
            - "b"
            - "both"
    enable:
      required: true
      selector:
        boolean:
